#!/usr/bin/env bash
#
# Automated seed pipeline: mini dry run → check oscillations → full run
# Tries seeds in order until one oscillates, then runs full pipeline.
#
set -euo pipefail

SEEDS=(137 271 314)
WD=0.5
LR=0.001
LP=2.0
LOG_FILE="run_seed_auto.log"

exec > >(tee -a "$LOG_FILE") 2>&1

echo "========================================================================"
echo "  AUTOMATED SEED PIPELINE"
echo "  Seeds to try: ${SEEDS[*]}"
echo "  Started: $(date)"
echo "========================================================================"

CHOSEN_SEED=""

for SEED in "${SEEDS[@]}"; do
    echo ""
    echo "════════════════════════════════════════════════════════════════════════"
    echo "  MINI DRY RUN: seed=${SEED} (2K steps)"
    echo "════════════════════════════════════════════════════════════════════════"

    DRY_DIR="runs/pilot_wd${WD}_lr${LR}_lp${LP}_s${SEED}_dryrun"

    # Run 2K-step dry run (separate dir so full run starts clean)
    python -u pilot.py \
        --seed "$SEED" \
        --wd "$WD" \
        --lr "$LR" \
        --lambda-probe "$LP" \
        --steps 2000 \
        --eval-every 100 \
        --p-probe 0.10 \
        --n-layer 8 \
        --d-model 512 \
        --n-head 16 \
        --d-ff 2048

    # The pilot.py saves to runs/pilot_wd0.5_lr0.001_lp2.0_s${SEED}/
    ACTUAL_DIR="runs/pilot_wd${WD}_lr${LR}_lp${LP}_s${SEED}"

    echo ""
    echo ">>> Checking for oscillations in ${ACTUAL_DIR}..."

    if python -u detect_oscillations.py --run-dir "$ACTUAL_DIR"; then
        echo ">>> Oscillations detected for seed ${SEED}!"
        CHOSEN_SEED="$SEED"
        break
    else
        echo ">>> No oscillations for seed ${SEED}, trying next..."
    fi
done

if [ -z "$CHOSEN_SEED" ]; then
    echo ""
    echo "ERROR: No seeds showed oscillations. Tried: ${SEEDS[*]}"
    echo "Consider trying different seeds or adjusting hyperparameters."
    exit 1
fi

echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "  FULL PIPELINE: seed=${CHOSEN_SEED}"
echo "  Mini dry run confirmed oscillations. Proceeding with 10K steps."
echo "════════════════════════════════════════════════════════════════════════"

# Clean up dry run artifacts so full run starts fresh
# Remove stage flags and checkpoints from the 2K dry run
RUN_DIR="runs/pilot_wd${WD}_lr${LR}_lp${LP}_s${CHOSEN_SEED}"
rm -rf "${RUN_DIR}/.stages"
# Keep codewords.json and config.json (they're seed-independent protocol files)
# Remove dry-run checkpoints and metrics (will be regenerated by full run)
rm -f "${RUN_DIR}"/ckpt_*.pt
rm -f "${RUN_DIR}/pilot_metrics.json"
rm -f "${RUN_DIR}/oscillation_manifest.json"
rm -rf "${RUN_DIR}/analysis"

echo ">>> Cleaned dry-run artifacts from ${RUN_DIR}"
echo ">>> Starting full pipeline..."

# Run the full pipeline
./run_seed.sh "$CHOSEN_SEED"

echo ""
echo "========================================================================"
echo "  FULL PIPELINE COMPLETE: seed=${CHOSEN_SEED}"
echo "  Finished: $(date)"
echo "========================================================================"
